# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLara():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://selenium:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_lara(self):
    self.driver.get("http://host.docker.internal:8089/")
    self.driver.set_window_size(883, 793)
